#!/bin/bash

# LGCSE Certificate Verification System - Manual Startup Commands
# This file contains all commands to run components from proper directories

echo "LGCSE Certificate Verification System - Manual Startup Commands"
echo "=============================================================="
echo ""

# Project root directory
PROJECT_ROOT="/home/duckey/lgcse-project"

echo "Project Root: $PROJECT_ROOT"
echo ""

echo "1. DATABASE SETUP"
echo "=================="
echo "# Setup PostgreSQL database"
echo "cd $PROJECT_ROOT/backend"
echo "source venv/bin/activate"
echo "python3 setup_database.py"
echo "cd $PROJECT_ROOT"
echo ""

echo "2. BLOCKCHAIN SETUP (Terminal 1)"
echo "================================="
echo "# Navigate to blockchain directory"
echo "cd $PROJECT_ROOT/blockchain"
echo ""
echo "# Install dependencies"
echo "npm install"
echo ""
echo "# Compile smart contracts"
echo "npm run compile"
echo ""
echo "# Start Hardhat local node"
echo "npm run node"
echo ""

echo "3. SMART CONTRACT DEPLOYMENT (Terminal 2)"
echo "=========================================="
echo "# Navigate to blockchain directory"
echo "cd $PROJECT_ROOT/blockchain"
echo ""
echo "# Deploy contracts to local node"
echo "npm run deploy"
echo ""

echo "4. BACKEND SERVER (Terminal 3)"
echo "==============================="
echo "# Navigate to backend directory"
echo "cd $PROJECT_ROOT/backend"
echo ""
echo "# Setup virtual environment"
echo "python3 -m venv venv"
echo "source venv/bin/activate"
echo ""
echo "# Install dependencies"
echo "pip install -r requirements.txt"
echo ""
echo "# Start FastAPI server"
echo "python3 main.py"
echo ""

echo "5. FRONTEND APPLICATION (Terminal 4)"
echo "====================================="
echo "# Navigate to frontend directory"
echo "cd $PROJECT_ROOT/frontend"
echo ""
echo "# Install dependencies"
echo "npm install"
echo ""
echo "# Start React application"
echo "npm start"
echo ""

echo "6. OPTIONAL: HYPERLEDGER FABRIC (Terminal 5)"
echo "============================================"
echo "# Navigate to Fabric directory"
echo "cd $PROJECT_ROOT/hyperledger-fabric"
echo ""
echo "# Make scripts executable"
echo "chmod +x scripts/*.sh"
echo ""
echo "# Run deployment menu"
echo "./scripts/deploy-menu.sh"
echo ""

echo "ENVIRONMENT CONFIGURATION"
echo "========================"
echo "# Backend environment file"
echo "cp $PROJECT_ROOT/backend/.env.example $PROJECT_ROOT/backend/.env"
echo ""
echo "# Frontend environment file"
echo "cp $PROJECT_ROOT/frontend/.env.example $PROJECT_ROOT/frontend/.env"
echo ""

echo "VERIFICATION COMMANDS"
echo "====================="
echo "# Check backend health"
echo "curl http://localhost:8000/health"
echo ""
echo "# Check API documentation"
echo "curl http://localhost:8000/docs"
echo ""
echo "# Check blockchain status"
echo "curl http://localhost:8000/api/blockchain/status"
echo ""
echo "# Verify database connection"
echo "cd $PROJECT_ROOT/backend && python3 verify_database.py"
echo ""

echo "SERVICE URLs"
echo "============"
echo "• Backend API:     http://localhost:8000"
echo "• Frontend App:    http://localhost:3000"
echo "• Blockchain Node: http://localhost:8545"
echo "• API Docs:        http://localhost:8000/docs"
echo ""

echo "QUICK START COMMANDS"
echo "===================="
echo "# For automated startup, use:"
echo "./start-complete.sh"
echo ""
echo "# For automated startup with Fabric:"
echo "./start-complete.sh --fabric"
echo ""

echo "SYSTEM FEATURES"
echo "==============="
echo "• Enhanced OCR Processing (88% accuracy)"
echo "• Multi-API OCR (OCR.space + Tesseract)"
echo "• Blockchain Certificate Verification"
echo "• Real-time Processing Updates"
echo "• Complete Diploma Management"
echo "• Hyperledger Fabric Support (optional)"
