#!/bin/bash

# LGCSE Certificate Verification System - Complete System Commands
# This script provides all commands for the complete system including database

echo "LGCSE Certificate Verification System - Complete Commands"
echo "======================================================"
echo ""

# Project directories
PROJECT_ROOT="/home/duckey/lgcse-project"
BACKEND_DIR="$PROJECT_ROOT/backend"
FRONTEND_DIR="$PROJECT_ROOT/frontend"
BLOCKCHAIN_DIR="$PROJECT_ROOT/blockchain"
FABRIC_DIR="$PROJECT_ROOT/hyperledger-fabric"

echo "Project Root: $PROJECT_ROOT"
echo ""

echo "COMPLETE SYSTEM STARTUP"
echo "======================"
echo ""

echo "1. DATABASE SETUP"
echo "================"
echo "# View all database commands"
echo "./database-commands.sh"
echo ""
echo "# Quick database setup"
echo "cd $BACKEND_DIR"
echo "source venv/bin/activate"
echo "python3 setup_database.py"
echo ""
echo "# Or install PostgreSQL manually"
echo "sudo apt update && sudo apt install postgresql postgresql-contrib"
echo "sudo systemctl start postgresql"
echo "sudo -u postgres psql -c \"CREATE USER lgcsedb WITH PASSWORD 'lgcsedb123';\""
echo "sudo -u postgres psql -c \"CREATE DATABASE lgcsedb OWNER lgcsedb;\""
echo "sudo -u postgres psql -c \"GRANT ALL PRIVILEGES ON DATABASE lgcsedb TO lgcsedb;\""
echo ""

echo "2. MAIN SYSTEM STARTUP"
echo "===================="
echo "# Automated complete startup"
echo "./start-complete.sh"
echo ""
echo "# Or with Hyperledger Fabric"
echo "./start-complete.sh --fabric"
echo ""
echo "# Manual startup (4 terminals):"
echo "Terminal 1: cd $BLOCKCHAIN_DIR && npm install && npm run compile && npm run node"
echo "Terminal 2: cd $BLOCKCHAIN_DIR && npm run deploy"
echo "Terminal 3: cd $BACKEND_DIR && source venv/bin/activate && python3 main.py"
echo "Terminal 4: cd $FRONTEND_DIR && npm install && npm start"
echo ""

echo "3. INSTITUTION NODES SETUP"
echo "=========================="
echo "# Setup all institution nodes (requires Fabric running)"
echo "./setup-institution-nodes.sh"
echo ""
echo "# View institution commands"
echo "./institution-commands.sh"
echo ""
echo "# Monitor institution nodes"
echo "./hyperledger-fabric/monitoring/monitoring-dashboard.sh"
echo ""

echo "4. HYPERLEDGER FABRIC NETWORK"
echo "============================"
echo "# Deploy Fabric network with menu"
echo "cd $FABRIC_DIR"
echo "./scripts/deploy-menu.sh"
echo ""
echo "# Quick deployment options"
echo "./scripts/deploy-menu.sh --minimal    # Low resource"
echo "./scripts/deploy-menu.sh --standard   # Development"
echo "./scripts/deploy-menu.sh --full       # Production"
echo ""

echo "5. SERVICE URLS AND ACCESS"
echo "========================"
echo "• Backend API:     http://localhost:8000"
echo "• Frontend App:    http://localhost:3000"
echo "• Blockchain Node: http://localhost:8545"
echo "• API Docs:        http://localhost:8000/docs"
echo ""
echo "• Ecol University:     Peer: 7051, CA: 8054"
echo "• Limkokwing University: Peer: 9051, CA: 9054"
echo "• Botho University:     Peer: 11051, CA: 10054"
echo "• NUL University:       Peer: 12051, CA: 11054"
echo ""

echo "6. VERIFICATION COMMANDS"
echo "======================"
echo ""
echo "# Check all services"
echo "curl http://localhost:8000/health"
echo ""
echo "# Check database connection"
echo "cd $BACKEND_DIR && source venv/bin/activate && python3 verify_database.py"
echo ""
echo "# Check blockchain status"
echo "curl http://localhost:8000/api/blockchain/status"
echo ""
echo "# Monitor institution nodes"
echo "./hyperledger-fabric/monitoring/monitoring-dashboard.sh"
echo ""

echo "7. ENVIRONMENT CONFIGURATION"
echo "=========================="
echo ""
echo "# Backend environment"
echo "cd $BACKEND_DIR"
echo "cp .env.example .env"
echo "# Edit .env with:"
echo "DATABASE_URL=postgresql://lgcsedb:lgcsedb123@localhost:5432/lgcsedb"
echo "SECRET_KEY=your-secret-key-here"
echo "ISSUER_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
echo ""
echo "# Frontend environment"
echo "cd $FRONTEND_DIR"
echo "cp .env.example .env"
echo "# Edit with backend URL and API keys"
echo ""

echo "8. DEPENDENCY INSTALLATION"
echo "========================"
echo ""
echo "# Install all dependencies"
echo "./install.sh"
echo ""
echo "# Manual installation:"
echo "cd $BACKEND_DIR && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt"
echo "cd $FRONTEND_DIR && npm install"
echo "cd $BLOCKCHAIN_DIR && npm install"
echo ""

echo "9. TROUBLESHOOTING"
echo "==============="
echo ""
echo "# If port conflicts occur:"
echo "sudo lsof -i :8000  # Backend port"
echo "sudo lsof -i :3000  # Frontend port"
echo "sudo lsof -i :8545  # Blockchain port"
echo ""
echo "# If Docker issues:"
echo "sudo systemctl status docker"
echo "sudo systemctl restart docker"
echo "docker system prune -f"
echo ""
echo "# If PostgreSQL issues:"
echo "sudo systemctl status postgresql"
echo "sudo systemctl restart postgresql"
echo "sudo tail -f /var/log/postgresql/postgresql-*-main.log"
echo ""

echo "10. QUICK START SEQUENCE"
echo "======================"
echo ""
echo "# Complete startup sequence:"
echo "1. ./install.sh                    # Install dependencies"
echo "2. ./database-commands.sh          # Setup database"
echo "3. ./start-complete.sh              # Start main services"
echo "4. ./setup-institution-nodes.sh     # Setup institution nodes"
echo "5. ./hyperledger-fabric/monitoring/monitoring-dashboard.sh  # Monitor"
echo ""
echo "# Alternative with Fabric:"
echo "1. ./install.sh"
echo "2. ./database-commands.sh"
echo "3. cd $FABRIC_DIR && ./scripts/deploy-menu.sh --standard"
echo "4. ./start-complete.sh --fabric"
echo "5. ./setup-institution-nodes.sh"
echo ""

echo "SYSTEM FEATURES"
echo "==============="
echo "• Enhanced OCR Processing (88% accuracy)"
echo "• Multi-API OCR (OCR.space + Tesseract)"
echo "• Blockchain Certificate Verification"
echo "• Real-time Processing Updates"
echo "• Complete Diploma Management"
echo "• Multi-Institution Network"
echo "• Hyperledger Fabric Support"
echo "• PostgreSQL/SQLite Database"
echo "• Institution-Specific Nodes"
echo "• Certificate Issuance & Verification"
echo "• User Management & Access Control"
