#!/bin/bash

# LGCSE Certificate Verification System - Institution Node Commands
# This script provides commands to manage individual institution nodes

echo "LGCSE Certificate Verification System - Institution Node Commands"
echo "================================================================="
echo ""

# Project directories
PROJECT_ROOT="/home/duckey/lgcse-project"
FABRIC_DIR="$PROJECT_ROOT/hyperledger-fabric"

echo "Project Root: $PROJECT_ROOT"
echo "Fabric Directory: $FABRIC_DIR"
echo ""

echo "INSTITUTION NODES STRUCTURE"
echo "============================"
echo ""

echo "1. ECOL UNIVERSITY (Issuer)"
echo "=========================="
echo "• Peer Node: peer0.ecol.example.com:7051"
echo "• CA Port: 8054"
echo "• Container: ca_ecol"
echo "• Role: Certificate Issuer"
echo ""
echo "# Start ECOL Node"
echo "cd $FABRIC_DIR"
echo "docker-compose up -d ca_ecol peer0.ecol.example.com"
echo ""
echo "# ECOL CLI Commands"
echo "cd $FABRIC_DIR/cli-ecol"
echo "./institution-commands.sh"
echo ""
echo "# ECOL User Management"
echo "cd $FABRIC_DIR/enrollment-ecol"
echo "./enroll-admin.sh"
echo "./register-user.sh <username>"
echo ""

echo "2. LIMKOWING UNIVERSITY (Verifier)"
echo "=================================="
echo "• Peer Node: peer0.limkokwing.example.com:9051"
echo "• CA Port: 9054"
echo "• Container: ca_limkokwing"
echo "• Role: Certificate Verifier"
echo ""
echo "# Start Limkokwing Node"
echo "cd $FABRIC_DIR"
echo "docker-compose up -d ca_limkokwing peer0.limkokwing.example.com"
echo ""
echo "# Limkokwing CLI Commands"
echo "cd $FABRIC_DIR/cli-limkokwing"
echo "./institution-commands.sh"
echo ""
echo "# Limkokwing User Management"
echo "cd $FABRIC_DIR/enrollment-limkokwing"
echo "./enroll-admin.sh"
echo "./register-user.sh <username>"
echo ""

echo "3. BOTHO UNIVERSITY (Verifier)"
echo "=============================="
echo "• Peer Node: peer0.botho.example.com:11051"
echo "• CA Port: 10054"
echo "• Container: ca_botho"
echo "• Role: Certificate Verifier"
echo ""
echo "# Start Botho Node"
echo "cd $FABRIC_DIR"
echo "docker-compose up -d ca_botho peer0.botho.example.com"
echo ""
echo "# Botho CLI Commands"
echo "cd $FABRIC_DIR/cli-botho"
echo "./institution-commands.sh"
echo ""
echo "# Botho User Management"
echo "cd $FABRIC_DIR/enrollment-botho"
echo "./enroll-admin.sh"
echo "./register-user.sh <username>"
echo ""

echo "4. NATIONAL UNIVERSITY OF LESOTHO (Verifier)"
echo "=========================================="
echo "• Peer Node: peer0.nul.example.com:12051"
echo "• CA Port: 11054"
echo "• Container: ca_nul"
echo "• Role: Certificate Verifier"
echo ""
echo "# Start NUL Node"
echo "cd $FABRIC_DIR"
echo "docker-compose up -d ca_nul peer0.nul.example.com"
echo ""
echo "# NUL CLI Commands"
echo "cd $FABRIC_DIR/cli-nul"
echo "./institution-commands.sh"
echo ""
echo "# NUL User Management"
echo "cd $FABRIC_DIR/enrollment-nul"
echo "./enroll-admin.sh"
echo "./register-user.sh <username>"
echo ""

echo "AUTOMATED SETUP COMMANDS"
echo "========================"
echo ""
echo "# Setup all institution nodes automatically"
echo "./setup-institution-nodes.sh"
echo ""
echo "# Monitor all institution nodes"
echo "$FABRIC_DIR/monitoring/monitoring-dashboard.sh"
echo ""

echo "CERTIFICATE OPERATIONS BY INSTITUTION"
echo "======================================"
echo ""

echo "ECOL UNIVERSITY (Issuer) - Certificate Issuance"
echo "-----------------------------------------------"
echo "# Issue new certificate"
echo "cd $FABRIC_DIR/cli-ecol"
echo "export CORE_PEER_TLS_ENABLED=true"
echo "export CORE_PEER_LOCALMSPID=EcolOrgMSP"
echo "export CORE_PEER_TLS_ROOTCERT_FILE=\$PWD/organizations/peerOrganizations/ecol.example.com/peers/peer0.ecol.example.com/tls/ca.crt"
echo "export CORE_PEER_MSPCONFIGPATH=\$PWD/organizations/peerOrganizations/ecol.example.com/users/Admin@ecol.example.com/msp"
echo "export CORE_PEER_ADDRESS=peer0.ecol.example.com:7051"
echo ""
echo "peer chaincode invoke -C lgcse-channel -n certificate-chaincode -c '{\"Args\":[\"IssueCertificate\",\"CERT_001\",\"STU001\",\"John\",\"Doe\",2023,\"[{\\\"name\\\":\\\"Mathematics\\\",\\\"grade\\\":\\\"A\\\",\\\"symbol\\\":\\\"*\\\"}]\",\"5\",\"2023-12-01\",\"Ecol University\",\"ECOL\",\\\"\\\"]}' --peerAddresses peer0.ecol.example.com:7051 --tlsRootCertFiles \$CORE_PEER_TLS_ROOTCERT_FILE"
echo ""

echo "ALL INSTITUTIONS (Verifiers) - Certificate Verification"
echo "------------------------------------------------------"
echo "# Verify certificate (any verifier institution)"
echo "cd $FABRIC_DIR/cli-limkokwing  # or cli-botho, cli-nul"
echo "export CORE_PEER_TLS_ENABLED=true"
echo "export CORE_PEER_LOCALMSPID=LimkokwingOrgMSP  # or BothoOrgMSP, NulOrgMSP"
echo "export CORE_PEER_TLS_ROOTCERT_FILE=\$PWD/organizations/peerOrganizations/limkokwing.example.com/peers/peer0.limkokwing.example.com/tls/ca.crt"
echo "export CORE_PEER_MSPCONFIGPATH=\$PWD/organizations/peerOrganizations/limkokwing.example.com/users/Admin@limkokwing.example.com/msp"
echo "export CORE_PEER_ADDRESS=peer0.limkokwing.example.com:9051"
echo ""
echo "peer chaincode invoke -C lgcse-channel -n certificate-chaincode -c '{\"Args\":[\"VerifyCertificate\",\"CERT_001\",\"VER001\",\"Alice Smith\",\"LIMKOWING\",\"hash\",\"192.168.1.100\",\"Mozilla/5.0\",\\\"\\\"]}' --peerAddresses peer0.limkokwing.example.com:9051 --tlsRootCertFiles \$CORE_PEER_TLS_ROOTCERT_FILE"
echo ""

echo "QUERIES AND MONITORING"
echo "======================"
echo ""
echo "# Query all certificates"
echo "peer chaincode query -C lgcse-channel -n certificate-chaincode -c '{\"Args\":[\"GetAllCertificates\"]}'"
echo ""
echo "# Query specific certificate"
echo "peer chaincode query -C lgcse-channel -n certificate-chaincode -c '{\"Args\":[\"GetCertificate\",\"CERT_001\"]}'"
echo ""
echo "# Query verification history"
echo "peer chaincode query -C lgcse-channel -n certificate-chaincode -c '{\"Args\":[\"GetVerificationHistory\",\"CERT_001\"]}'"
echo ""
echo "# Query network statistics"
echo "peer chaincode query -C lgcse-channel -n certificate-chaincode -c '{\"Args\":[\"GetNetworkStatistics\"]}'"
echo ""

echo "NODE MANAGEMENT COMMANDS"
echo "========================"
echo ""
echo "# Check node status"
echo "docker-compose ps"
echo ""
echo "# View node logs"
echo "docker-compose logs -f ca_ecol"
echo "docker-compose logs -f peer0.ecol.example.com"
echo ""
echo "# Restart specific node"
echo "docker-compose restart ca_ecol"
echo "docker-compose restart peer0.ecol.example.com"
echo ""
echo "# Stop all nodes"
echo "docker-compose stop"
echo ""
echo "# Start all nodes"
echo "docker-compose start"
echo ""

echo "NETWORK PORTS SUMMARY"
echo "====================="
echo "• Orderer: 7050"
echo "• Orderer CA: 7054"
echo "• Ecol Peer: 7051"
echo "• Ecol CA: 8054"
echo "• Limkokwing Peer: 9051"
echo "• Limkokwing CA: 9054"
echo "• Botho Peer: 11051"
echo "• Botho CA: 10054"
echo "• NUL Peer: 12051"
echo "• NUL CA: 11054"
echo ""

echo "QUICK START GUIDE"
echo "================="
echo "1. Start Fabric network: cd $FABRIC_DIR && ./scripts/deploy-menu.sh"
echo "2. Setup institution nodes: ./setup-institution-nodes.sh"
echo "3. Monitor nodes: $FABRIC_DIR/monitoring/monitoring-dashboard.sh"
echo "4. Use institution CLI: cd $FABRIC_DIR/cli-ecol && ./institution-commands.sh"
echo "5. Issue certificates (ECOL): Use ECOL CLI to issue certificates"
echo "6. Verify certificates (All): Use any verifier CLI to verify certificates"
