#!/usr/bin/env python3
"""
M-Pesa Setup Helper for CertiVert
This script helps you configure M-Pesa credentials for testing
"""

import os
import sys
from pathlib import Path

def setup_mpesa_credentials():
    """Interactive setup for M-Pesa credentials"""
    
    print("🔧 M-Pesa Configuration Setup for CertiVert")
    print("=" * 50)
    print()
    
    print("To test M-Pesa payments, you need:")
    print("1. M-Pesa Developer Account (from Safaricom Developer Portal)")
    print("2. Test Shortcode and Passkey")
    print("3. Consumer Key and Secret")
    print()
    
    # Get credentials from user
    credentials = {}
    
    print("📝 Enter your M-Pesa credentials:")
    print("(Press Enter to skip if you don't have them yet)")
    print()
    
    credentials['consumer_key'] = input("Consumer Key: ").strip()
    credentials['consumer_secret'] = input("Consumer Secret: ").strip()
    credentials['passkey'] = input("Passkey: ").strip()
    credentials['shortcode'] = input("Shortcode: ").strip()
    
    # Get test phone number
    print()
    credentials['phone_number'] = input("Your Test M-Pesa Number (+2665XXXXXXXXX): ").strip()
    
    # Environment selection
    print()
    print("Select environment:")
    print("1. Sandbox (for testing - no real money)")
    print("2. Production (real transactions)")
    
    env_choice = input("Enter choice (1 or 2): ").strip()
    credentials['environment'] = 'production' if env_choice == '2' else 'sandbox'
    
    # Generate .env file
    env_content = f"""# M-Pesa Lesotho Configuration - Generated by Setup Script
# Environment: {credentials['environment']}

MPESA_CONSUMER_KEY={credentials['consumer_key']}
MPESA_CONSUMER_SECRET={credentials['consumer_secret']}
MPESA_PASSKEY={credentials['passkey']}
MPESA_SHORTCODE={credentials['shortcode']}
MPESA_CALLBACK_URL=http://localhost:8000/api/mpesa/callback
MPESA_ENVIRONMENT={credentials['environment']}

# Test Configuration
TEST_PHONE_NUMBER={credentials['phone_number']}
TEST_AMOUNT=1.00

# Database
DATABASE_URL=postgresql://diploma_admin:diploma1234@localhost:5432/diploma_verification
SECRET_KEY=certivert-payment-test-secret-key-change-in-production

# OCR Configuration (already working)
OCR_SPACE_API_KEY=8195ce015388957
GOOGLE_CLOUD_VISION_API_KEY=your_google_cloud_vision_api_key_here
GEMINI_API_KEY=AIzaSyAi_sGYVRruxiuT4mMP3k_khOxpJ_VIOGg
"""
    
    # Save to .env file
    env_path = Path(__file__).parent / ".env"
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print()
    print("✅ Configuration saved to .env file")
    print()
    
    # Next steps
    print("📋 Next Steps:")
    print("1. Start the backend server:")
    print("   cd backend && source venv/bin/activate && python -m uvicorn main:app --host 0.0.0.0 --port 8000")
    print()
    print("2. Open the payment monitor in your browser:")
    print("   file:///home/duckey/lgcse-project/mpesa_monitor.html")
    print()
    print("3. Enter your M-Pesa number and click 'Send STK Push'")
    print()
    print("4. Check your phone for the STK prompt and:")
    print("   - Enter CORRECT PIN to test successful payment")
    print("   - Enter INCORRECT PIN to test failure handling")
    print()
    
    if credentials['environment'] == 'production':
        print("⚠️  WARNING: You're using PRODUCTION environment!")
        print("   Real money will be deducted from your M-Pesa account!")
        print("   Use small amounts (1.00 LSL) for testing.")
        print()
    else:
        print("ℹ️  You're using SANDBOX environment")
        print("   No real money will be charged")
        print()
    
    # Test configuration
    print("🧪 Testing configuration...")
    
    # Load environment variables
    from dotenv import load_dotenv
    load_dotenv(env_path)
    
    # Check if credentials are set
    missing = []
    for key in ['MPESA_CONSUMER_KEY', 'MPESA_CONSUMER_SECRET', 'MPESA_PASSKEY', 'MPESA_SHORTCODE']:
        if not os.getenv(key):
            missing.append(key)
    
    if missing:
        print(f"❌ Missing credentials: {', '.join(missing)}")
        print("Please update the .env file with your actual M-Pesa credentials")
        return False
    else:
        print("✅ All M-Pesa credentials configured!")
        return True

def show_webhook_info():
    """Show webhook configuration information"""
    print()
    print("📡 Webhook Callback Information:")
    print("=" * 40)
    print()
    print("Callback URL: http://localhost:8000/api/mpesa/callback")
    print()
    print("For M-Pesa to send callbacks to your local server:")
    print("1. Your server must be running on port 8000")
    print("2. The URL must be accessible from the internet")
    print("3. For local testing, use a tunnel service like:")
    print("   - ngrok: ngrok http 8000")
    print("   - cloudflare: cloudflared tunnel --url http://localhost:8000")
    print()
    print("Then update MPESA_CALLBACK_URL in .env to the tunnel URL")

if __name__ == "__main__":
    try:
        success = setup_mpesa_credentials()
        show_webhook_info()
        
        if success:
            print("\n🎉 Setup complete! You can now test M-Pesa payments.")
        else:
            print("\n⚠️  Setup incomplete. Please add your M-Pesa credentials.")
            
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Setup error: {e}")
        sys.exit(1)
