OrdererOrgs:
  - Name: Orderer
    Domain: certivert.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.certivert.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.certivert.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
